# Generated by Django 4.1.3 on 2022-11-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата измерения'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.IntegerField(verbose_name='Температура при измерении'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
