# Generated by Django 4.1.3 on 2022-11-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_rename_measurement_measurement_measurement_sensor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurement_sensor',
            new_name='sensor',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата измерения'),
        ),
    ]
